import {useEffect,useMemo,useState} from 'react';
import type {Identity,CalcInput,ApplicationView,Calculation} from '../types';
import {calculate,create,getApplication,search,updateApplication,action} from '../api/client';
import {FeeCard} from '../components/FeeCard'; import {Timeline} from '../components/Timeline';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const empty=(tenant:string):CalcInput=>({tenantId:tenant,roadType:'BT',lengthInMeters:1,widthInMeters:1,durationInDays:1,applicantType:'PRIVATE',proposedStartDate:today()});
export function ApplicantPage({identity}:{identity:Identity}){
 const [form,setForm]=useState<CalcInput>(empty(identity.tenantId)); const [mobile,setMobile]=useState(identity.userName); const [calc,setCalc]=useState<Calculation|null>(null); const [apps,setApps]=useState<ApplicationView[]>([]); const [selected,setSelected]=useState<ApplicationView|null>(null); const [editing,setEditing]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{setForm(empty(identity.tenantId));setMobile(identity.userName);setCalc(null);setSelected(null);load();},[identity.uuid]);
 useEffect(()=>{const t=setTimeout(async()=>{if(form.lengthInMeters>0&&form.widthInMeters>0&&form.durationInDays>0&&form.proposedStartDate){try{const r=await calculate(identity,form);setCalc(r.Calculation);setError('')}catch(e){setError((e as Error).message);setCalc(null)}}},450);return()=>clearTimeout(t)},[form,identity]);
 async function load(){try{const r=await search(identity,{});setApps(r.applications)}catch(e){setError((e as Error).message)}}
 const set=(k:keyof CalcInput,v:string)=>setForm(f=>({...f,[k]:['lengthInMeters','widthInMeters','durationInDays'].includes(k)?Number(v):v}));
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await create(identity,{...form,mobileNumber:mobile});await load();setForm(empty(identity.tenantId));setCalc(null);alert('Application submitted successfully.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function open(a:ApplicationView){try{const r=await getApplication(identity,a.applicationNumber);setSelected(r.Application)}catch(e){setError((e as Error).message)}}
 async function saveEdit(){if(!selected)return;setBusy(true);try{const r=await updateApplication(identity,{...form,mobileNumber:mobile,applicationNumber:selected.applicationNumber});setSelected(r.Application);setEditing(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const editable=selected?.status==='APPLIED';
 return <div className="app-grid"><section className="panel"><h2>{editing?'Edit application':'New road-cutting application'}</h2><form onSubmit={editing?e=>{e.preventDefault();saveEdit()}:submit}>
  <label>Mobile number<input value={mobile} onChange={e=>setMobile(e.target.value)} required/></label>
  <div className="two"><label>Road type<select value={form.roadType} onChange={e=>set('roadType',e.target.value)}><option>BT</option><option>CC</option><option>WBM</option><option>KUTCHA</option></select></label><label>Applicant type<select value={form.applicantType} onChange={e=>set('applicantType',e.target.value as any)}><option value="PRIVATE">Private</option><option value="GOVERNMENT_AGENCY">Government agency</option></select></label></div>
  <div className="two"><label>Length (m)<input type="number" min="0.001" step="0.001" value={form.lengthInMeters} onChange={e=>set('lengthInMeters',e.target.value)} required/></label><label>Width (m)<input type="number" min="0.001" step="0.001" value={form.widthInMeters} onChange={e=>set('widthInMeters',e.target.value)} required/></label></div>
  <div className="two"><label>Duration (days)<input type="number" min="1" max="365" value={form.durationInDays} onChange={e=>set('durationInDays',e.target.value)} required/></label><label>Proposed start<input type="date" min={today()} value={form.proposedStartDate} onChange={e=>set('proposedStartDate',e.target.value)} required/></label></div>
  <FeeCard calc={calc}/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{editing?'Save changes':'Submit application'}</button>{editing&&<button type="button" className="secondary" onClick={()=>setEditing(false)}>Cancel</button>}</form></section>
  <section className="panel"><h2>My applications</h2>{apps.length===0?<div className="empty">No applications yet.</div>:<div className="cards">{apps.map(a=><button className="app-card" key={a.applicationNumber} onClick={()=>open(a)}><b>{a.applicationNumber}</b><span>{a.roadType} · {a.status}</span><span>₹{a.Calculation.totalAmount.toLocaleString('en-IN')}</span></button>)}</div>}
  {selected&&<div className="detail"><div className="detail-head"><div><h3>{selected.applicationNumber}</h3><span className="badge">{selected.status}</span></div><div className="actions">{editable&&<button className="secondary" onClick={()=>{setForm({tenantId:selected.tenantId,roadType:selected.roadType,lengthInMeters:selected.lengthInMeters,widthInMeters:selected.widthInMeters,durationInDays:selected.durationInDays,applicantType:selected.applicantType as any,proposedStartDate:selected.proposedStartDate});setMobile(selected.mobileNumber);setEditing(true)}}>Edit</button>}{selected.availableActions.map(a=><button key={a} onClick={async()=>{try{const r=await action(identity,selected.applicationNumber,a,'');setSelected(r.Application);await load()}catch(e){setError((e as Error).message)}}}>{a.replace('_',' ')}</button>)}</div></div><FeeCard calc={selected.Calculation}/><Timeline items={selected.history}/></div>}
 </section></div>
}
